### ISSUE TITLE
Basic version of this library

### ISSUE THREAD

**Issue by JenieX** [eight04/GM_webextPref#9]
I wanted to use it in some of my user scripts, and I was going to propose this library to @y252328, to use it in his user script [Instagram_Download_Button](https://github.com/y252328/Instagram_Download_Button) as well. 

Looking at the code now, it is too large and far more than the code of our user scripts. 
Maybe someday you will consider creating a super small version of this library, where it is specific to one website and with few basic options ,to make the code smaller. I would do it myself, but I'm not sure I fully grasp how to use this library, let alone understand the code to create a smaller version. 😄

**Comment by eight04** [comment]
I don't think removing scope support would make it any smaller. Here is the logic related to the scope:
https://github.com/eight04/webext-pref/blob/9b68a1c3a510763d47292f61b1d8b388b5385b18/lib/pref.js

One improve could be to use a naive `createElement` instead of full-featured [jsx-dom](https://www.npmjs.com/package/jsx-dom).

**Comment by JenieX** [comment]
That is complicated for me to understand at the moment, so I can't give an opinion. 😄
